import ArgumentParser
import Foundation
import GrantivaCore

struct InitCommand: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "init",
        abstract: "Generate grantiva.yml (iOS) or grantiva-android.yml (Android) in the current directory."
    )

    @OptionGroup var verbosity: VerbosityOptions
    @OptionGroup var platformOptions: PlatformOptions

    @Option(name: .long, help: "Scheme name")
    var scheme: String?

    @Option(name: .long, help: "Bundle identifier")
    var bundleId: String?

    @Option(name: .long, help: "Application ID (Android)")
    var applicationId: String?

    func run() async throws {
        try await run(environment: ProcessInfo.processInfo.environment)
    }

    func run(environment: [String: String]) async throws {
        let fm = FileManager.default
        let cwd = fm.currentDirectoryPath

        let platform = try Self.platform(
            flag: platformOptions.platform,
            environment: environment,
            detected: PlatformResolver(directory: URL(fileURLWithPath: cwd, isDirectory: true)).detectFromDirectory()
        )
        try Self.checkFlags(for: platform, scheme: scheme, bundleId: bundleId, applicationId: applicationId)
        if platform == .android {
            let configPath = "\(cwd)/grantiva-android.yml"
            if fm.fileExists(atPath: configPath) {
                GrantivaLog.logger.info("grantiva-android.yml already exists — skipping")
                return
            }
            let yaml = Self.androidTemplate(
                module: Self.detectModule(in: cwd),
                applicationId: applicationId,
                emulator: "Pixel_8_API_35"
            )
            try yaml.write(toFile: configPath, atomically: true, encoding: .utf8)
            GrantivaLog.logger.info("Created grantiva-android.yml")
            return
        }

        // Generate grantiva.yml
        let configPath = "\(cwd)/grantiva.yml"
        if fm.fileExists(atPath: configPath) {
            GrantivaLog.logger.info("grantiva.yml already exists — skipping")
        } else {
            let (yaml, warnings) = Self.iosTemplate(
                scheme: scheme, detectedScheme: detectScheme(), bundleId: bundleId,
                newestIPhone: await SimulatorManager.live.newestIPhone()
            )
            try yaml.write(toFile: configPath, atomically: true, encoding: .utf8)
            GrantivaLog.logger.info("Created grantiva.yml")
            for warning in warnings { GrantivaLog.logger.warning("\(warning)") }
        }

    }

    /// Which platform to initialize. An explicit flag wins, then
    /// GRANTIVA_PLATFORM (an invalid value is an error, as for `run`);
    /// otherwise the project files decide, and a directory with none of them
    /// stays iOS, as `init` always was.
    static func platform(flag: Platform?, environment: [String: String] = [:], detected: [Platform]) throws -> Platform {
        if let flag { return flag }
        if let platform = try PlatformResolver(environment: environment).environmentPlatform() {
            return platform
        }
        switch detected.count {
        case 2:
            throw GrantivaError.invalidArgument(
                "Found both an Xcode project and Gradle settings. Pass --platform ios|android or set \(PlatformResolver.environmentKey)."
            )
        case 1:
            return detected[0]
        default:
            return .ios
        }
    }

    /// The iOS config, plus a warning for each value that is a guess rather
    /// than something read from the project or the host.
    static func iosTemplate(
        scheme: String?, detectedScheme: String?, bundleId: String?, newestIPhone: String?
    ) -> (yaml: String, warnings: [String]) {
        var warnings: [String] = []
        let schemeName: String
        if let name = scheme ?? detectedScheme {
            schemeName = name
        } else {
            schemeName = "MyApp"
            warnings.append("No Xcode project found; scheme \"MyApp\" is a placeholder. Edit grantiva.yml or pass --scheme.")
        }
        let simulator: String
        if let newestIPhone {
            simulator = newestIPhone
        } else {
            simulator = "iPhone 17 Pro"
            warnings.append("No installed iPhone simulator type found; simulator \"iPhone 17 Pro\" is a placeholder. Edit grantiva.yml.")
        }
        let bundleLine = bundleId.map { "bundle_id: \($0)" } ?? "# bundle_id: com.example.myapp"
        let yaml = """
        # Generated by grantiva init — commit this file
        scheme: \(schemeName)
        # workspace: \(schemeName).xcworkspace
        simulator: \(simulator)
        \(bundleLine)

        screens:
          - name: Home
            path: launch

        diff:
          # both must pass: threshold is a 0-1 fraction of differing pixels, perceptual_threshold is the mean CIE76 distance over differing pixels
          threshold: 0.02
          perceptual_threshold: 5.0

        # a11y:
        #   rules:
        #     - missing_label
        #     - small_tap_target
        """
        return (yaml, warnings)
    }

    /// Rejects a flag from the other platform by name, as `run` does,
    /// instead of writing a config file that silently drops it.
    static func checkFlags(for platform: Platform, scheme: String?, bundleId: String?, applicationId: String?) throws {
        let wrong: [(String, Bool)] = platform == .ios
            ? [("--application-id", applicationId != nil)]
            : [("--scheme", scheme != nil), ("--bundle-id", bundleId != nil)]
        if let offending = wrong.first(where: { $0.1 })?.0 {
            throw TargetOptions.otherPlatformFlagError(offending, platform: platform)
        }
    }

    static func androidTemplate(module: String, applicationId: String?, emulator: String) -> String {
        let idLine = applicationId.map { "application_id: \($0)" } ?? "# application_id: com.example.myapp   # read from the build when omitted"
        return """
        # Generated by grantiva init — commit this file
        platform: android
        module: \(module)
        variant: debug
        \(idLine)
        emulator: \(emulator)
        system_image: "system-images;android-35;google_apis;arm64-v8a"
        # Intel Macs: use "system-images;android-35;google_apis;x86_64"
        # build_args: ["-PsomeFlag=1"]

        screens:
          - name: Home
            path: launch

        diff:
          # both must pass: threshold is a 0-1 fraction of differing pixels, perceptual_threshold is the mean CIE76 distance over differing pixels
          threshold: 0.02
          perceptual_threshold: 5.0

        # a11y:
        #   rules:
        #     - missing_label
        #     - small_tap_target

        """
    }

    /// `app` when it has a build file, else the first module whose build
    /// file applies `com.android.application`, else `app`.
    static func detectModule(in directory: String) -> String {
        let fm = FileManager.default
        func buildFile(_ module: String) -> String? {
            ["build.gradle.kts", "build.gradle"].map { "\(directory)/\(module)/\($0)" }.first { fm.fileExists(atPath: $0) }
        }
        if buildFile("app") != nil { return "app" }
        let entries = ((try? fm.contentsOfDirectory(atPath: directory)) ?? []).sorted()
        for entry in entries where !entry.hasPrefix(".") {
            guard let file = buildFile(entry), let contents = try? String(contentsOfFile: file, encoding: .utf8),
                  contents.contains("com.android.application") else { continue }
            return entry
        }
        return "app"
    }

    private func detectScheme() -> String? {
        let fm = FileManager.default
        let cwd = fm.currentDirectoryPath
        guard let contents = try? fm.contentsOfDirectory(atPath: cwd) else { return nil }
        if let ws = contents.first(where: { $0.hasSuffix(".xcworkspace") && !$0.hasPrefix(".") }) {
            return String(ws.dropLast(".xcworkspace".count))
        }
        if let proj = contents.first(where: { $0.hasSuffix(".xcodeproj") }) {
            return String(proj.dropLast(".xcodeproj".count))
        }
        return nil
    }
}
