platform: android
module: app
variant: freeDebug
application_id: com.kylebrowning.landmarks
emulator: Pixel_8_API_35
flows:
  - .maestro/99-crash.yaml
  - .maestro/01-browse.yaml
  - .maestro/05-category.yaml
